# Single-stage development Dockerfile to save space
FROM docker.io/library/rust:1.84-bookworm

RUN echo "Forcing fresh plugin install v3..." && apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      openssl \
      libssl-dev \
      ca-certificates \
      libgstrtspserver-1.0-dev \
      libgstreamer1.0-dev \
      libgtk2.0-dev \
      protobuf-compiler \
      libglib2.0-dev \
      gstreamer1.0-tools \
      gstreamer1.0-plugins-base \
      gstreamer1.0-plugins-good \
      gstreamer1.0-plugins-bad \
      gstreamer1.0-plugins-ugly \
      gstreamer1.0-libav && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/src/neolink

COPY . .

RUN cargo build --release && \
    cp docker/entrypoint.sh /entrypoint.sh && \
    chmod +x /entrypoint.sh

ENV NEO_LINK_MODE="rtsp" NEO_LINK_PORT=8554
CMD /usr/local/src/neolink/target/release/neolink "${NEO_LINK_MODE}" --config /etc/neolink.toml
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE ${NEO_LINK_PORT}
